#!/bin/bash

curl_http()
{
  code="$(curl -o /dev/null -s "$1" -w "%{http_code}\n")"
  echo "$1 - $code"
}

list=("https://www.bing.com" "https://www.google.com")
urls=$(printf "%s\n" ${list[@]})


while read url ; do
  curl_http "$url"
done <<< "$urls"
