#!/bin/bash

#curl_http()
#{

#}

urls=("https://www.google.com" "https://www.bing.com")
for url in "${urls[@]}" ; do
  code="$(curl -o /dev/null -s "$url" -w "%{http_code}")"
  echo "$url - $code" 
done
